[package]
name = "validator"
version = "0.1.0"
authors = ["Akropolis Decentralised Ltd., <team@akropolis.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.8.0"
tokio = "0.1.22"
tokio-threadpool = "0.1.15"
futures = "0.1.29"
rustc-hex = "2.0.1"
ethabi = "8.0.1"
log = "0.4.0"
env_logger = "0.6.2"
dotenv = "0.14.1"
graphql_client = "0.8.0"
reqwest = "0.9.22"
serde = "1.0.101"
time = "0.1.42"

node-runtime = { git = 'https://github.com/akropolisio/akropolisos-substrate-node.git', branch = 'pricefetch', package = 'akropolisos-runtime' }

raw-transaction-builder = { path = 'raw-transaction-builder' }

substrate-bip39 = "0.3.1"
substrate-api-client = { git = 'https://github.com/scs/substrate-api-client.git', rev = '822b0fd7fe4df5dabdb3c60c75d12d36cccba2f2'}

[dependencies.consensus]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-aura'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.primitives]
features = ["full_crypto"]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '00a400f82539e2f78e8ddbcd98aea512c87c5f3c' # must match with 'rev' of 'sp-core' in substrate-api-client!

[dependencies.primitives-node]
features = ["full_crypto"]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-core'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-runtime'
rev = '3e651110aa06aa835790df63410a29676243fc54'

[dependencies.parity-codec]
default-features = false
features = ['derive']
version = '3.5'

[dependencies.codec]
package = "parity-scale-codec"
features = ["derive"]
version = "1.0.0"
default-features = false
